# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/secondhand_deal?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  #redis连接配置
  data:
    redis:
      database: 0
      port: 6379
      host: 124.71.37.187
      password: zxcvbnmasd
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0


